version: '3.8'

services:
  project_u_development_db:
    image: postgres
    container_name: project_u_development_db
    ports:
      - '5432:5432'
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev123

  project_u_test_db:
    image: postgres
    container_name: project_u_test_db
    ports:
      - '5434:5432'
    volumes:
      - db_test_volume:/var/lib/postgresql/data_test
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test123

volumes:
  db_volume:
  db_test_volume: